- name: milestone
  color: "1f77b4"
- name: research-log
  color: "17becf"
- name: ai-collaboration
  color: "9467bd"
- name: speculate
  color: "bcbd22"
- name: research
  color: "ff9999"
- name: design
  color: "ff7f0e"
- name: make
  color: "2ca02c"
- name: publish
  color: "8c564b"
- name: assess
  color: "e377c2"
- name: help-wanted
  color: "d62728"
- name: bug
  color: "d73a4a"