name: AI Collaboration Report
description: What did AI do, and how did you evaluate it?
title: "AI Collab: <short>"
labels: ["ai-collaboration"]
body:
  - type: textarea
    id: prompt
    attributes:
      label: Prompts / Tasks given to AI
  - type: textarea
    id: output
    attributes:
      label: AI Output Summary
  - type: textarea
    id: eval
    attributes:
      label: Your Evaluation (accuracy, bias, limits)
  - type: textarea
    id: integration
    attributes:
      label: What was accepted, modified, or rejected?