name: Setup Project Board
on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [setup-project]
  workflow_dispatch:

jobs:
  setup-project:
    runs-on: ubuntu-latest
    # Don't run in the template repository itself
    if: github.repository != 'CHI-CityTech/CHI-Research-Template'
    steps:
      - name: Check if project already exists
        id: check-project
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const { data: projects } = await github.rest.projects.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              
              const hasResearchProject = projects.some(p => p.name === "Research Progress");
              core.setOutput('exists', hasResearchProject);
              
              return hasResearchProject;
            } catch (error) {
              core.setOutput('exists', false);
              return false;
            }
            
      - name: Checkout repository
        if: steps.check-project.outputs.exists == 'false'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Replace template README with project README
        if: steps.check-project.outputs.exists == 'false'
        run: |
          if [ -f "README.template.md" ]; then
            echo "Replacing template README with project-specific README"
            mv README.template.md README.md
            git config user.name "CHI Template Setup"
            git config user.email "action@github.com"
            git add README.md
            git commit -m "Initialize project README from template" || echo "No changes to commit"
            git push || echo "Nothing to push"
            echo "README.md updated for new research project"
          else
            echo "No README.template.md found, skipping README replacement"
          fi
          
      - name: Create Project Board
        if: steps.check-project.outputs.exists == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            // Create a new project board
            const { data: project } = await github.rest.projects.createForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "Research Progress",
              body: "Track research milestones and tasks using Agile/Kanban methodology"
            });

            // Create columns in order
            const columns = [
              { name: "Backlog", note: "New issues and planned work" },
              { name: "In Progress", note: "Currently active work" },
              { name: "In Review", note: "Work ready for review or feedback" },
              { name: "Done", note: "Completed work" }
            ];

            for (const column of columns) {
              await github.rest.projects.createColumn({
                project_id: project.id,
                name: column.name,
                note: column.note
              });
            }

            console.log(`Created project board: ${project.html_url}`);
            
            // Add initial milestone card if this is a new repository
            if (github.event_name == 'repository_dispatch' || github.event.ref_type == 'repository') {
              const columns_response = await github.rest.projects.listColumns({
                project_id: project.id
              });
              
              const backlogColumn = columns_response.data.find(col => col.name === 'Backlog');
              
              await github.rest.projects.createCard({
                column_id: backlogColumn.id,
                note: "Create your first milestone using the Milestone issue template"
              });
            }